version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_USERNAME=denis
      - SPRING_DATASOURCE_PASSWORD=123456aaa
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=denis
      - POSTGRES_PASSWORD=123456aaa